#!/usr/bin/env python3
"""Emit the GLYPHS blob that simulator.html pastes in, so the simulator draws the
panel's ACTUAL bitmap glyphs instead of standing an outline face in for them.

Why this exists: the simulator used to approximate the FreeSans GFX faces with
Helvetica sized to match their cap height, which was close enough because
FreeSans essentially IS Helvetica. The built-in faces are narrow bitmap fonts —
Font 2's 'O' advances 8px at a 10px cap height where Helvetica needs ~11 — so the
same trick draws glyphs wider than their advances and they visibly collide. Since
a bitmap font is fully determined, the honest fix is to ship the real pixels:
the simulator is now WYSIWYG rather than indicative.

Emits the raw byte streams from the library sources plus the offsets to index
them, base64'd. simulator.html re-implements the same two decoders (Font 2 row
bitmap, Font 4 RLE, GLCD columns) that TFT_eSPI's drawChar uses.

    python3 scripts/gen_sim_fonts.py >> /tmp/glyphs.js
"""
import base64
import os
import re

LIB = os.environ.get(
    "TFT_ESPI_FONTS",
    os.path.join(os.path.dirname(__file__), os.pardir,
                 ".pio", "libdeps", "cyd", "TFT_eSPI", "Fonts"),
)


def _clean(src, defines=None):
    src = re.sub(r"//[^\n]*", "", src)
    if defines is not None:
        src = re.sub(r"#ifdef\s+(\w+)(.*?)(?:#else(.*?))?#endif",
                     lambda m: m.group(2) if m.group(1) in defines else (m.group(3) or ""),
                     src, flags=re.S)
    return src


def load(name, tag):
    raw = open(os.path.join(LIB, name + ".c")).read()
    defines = set(re.findall(r"^\s*#define\s+(\w+)", raw, re.M))
    src = _clean(raw, defines)
    wm = re.search(r"widtbl_%s\[96\]\s*=\s*\{(.*?)\}" % tag, src, re.S)
    widths = [int(v) for v in re.findall(r"\d+", wm.group(1))][:96]
    glyphs = {}
    for m in re.finditer(r"chr_%s_([0-9A-Fa-f]{2})\s*\[[^\]]*\]\s*=\s*\{(.*?)\}" % tag,
                         src, re.S):
        glyphs[int(m.group(1), 16)] = bytes(
            int(x, 0) for x in re.findall(r"0x[0-9A-Fa-f]+|\b\d+\b", m.group(2)))
    return widths, glyphs


def blob(widths, glyphs, first=0x20, last=0x7E):
    """Concatenate glyph bytes and record where each one starts."""
    data, offs = bytearray(), []
    for c in range(first, last + 1):
        offs.append(len(data))
        data += glyphs.get(c, b"")
    offs.append(len(data))
    return widths[:last - first + 1], base64.b64encode(bytes(data)).decode(), offs


w16, g16 = load("Font16", "f16")
w32, g32 = load("Font32rle", "f32")

# GLCD: 5 column-bytes per char, bit N = row N. TFT_eSPI draws those 5 columns
# plus one blank, 8 rows tall, which is the 6x8 cell F_MICRO measures as.
glcd_src = _clean(open(os.path.join(LIB, "glcdfont.c")).read())
glcd = [int(x, 0) for x in re.findall(r"0x[0-9A-Fa-f]+", glcd_src)]
glcd_b64 = base64.b64encode(bytes(glcd[0x20 * 5:(0x7E + 1) * 5])).decode()

bw16, d16, o16 = blob(w16, g16)
bw32, d32, o32 = blob(w32, g32)

print("// GENERATED by scripts/gen_sim_fonts.py — do not hand-edit.")
print("// Real glyph data for TFT_eSPI's built-in faces, so the canvas below draws")
print("// the same pixels the panel does. Font 2 is a row bitmap, Font 4 is 8-bit")
print("// RLE, Font 1 (GLCD) is 5 column bytes per char; all three decoders mirror")
print("// TFT_eSPI::drawChar. Chars 0x20..0x7E only — the UI draws nothing else.")
print("const GLYPHS={")
print(f" F2:{{h:16,w:[{','.join(map(str, bw16))}],o:[{','.join(map(str, o16))}],")
print(f"     d:\"{d16}\"}},")
print(f" F4:{{h:26,w:[{','.join(map(str, bw32))}],o:[{','.join(map(str, o32))}],")
print(f"     d:\"{d32}\"}},")
print(f" F1:{{h:8,d:\"{glcd_b64}\"}},")
print("};")
